# Generated by Django 5.2 on 2025-05-06 17:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CargoType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Тип груза')),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Статус доставки')),
            ],
        ),
        migrations.CreateModel(
            name='PackagingType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Тип упаковки')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Услуга')),
            ],
        ),
        migrations.CreateModel(
            name='TransportModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Модель транспорта')),
            ],
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transport_number', models.CharField(max_length=50, verbose_name='Номер транспорта')),
                ('departure_time', models.DateTimeField(verbose_name='Время отправки')),
                ('arrival_time', models.DateTimeField(verbose_name='Время доставки')),
                ('distance_km', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Дистанция (км)')),
                ('media_file', models.FileField(blank=True, null=True, upload_to='deliveries/media/', verbose_name='Медиафайл')),
                ('technical_state', models.CharField(choices=[('good', 'Исправно'), ('bad', 'Неисправно')], default='good', max_length=4, verbose_name='Техническое состояние')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('cargo_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to='app.cargotype', verbose_name='Тип груза')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_deliveries', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deliveries', to='app.deliverystatus', verbose_name='Статус')),
                ('packaging', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deliveries', to='app.packagingtype', verbose_name='Упаковка')),
                ('services', models.ManyToManyField(blank=True, related_name='deliveries', to='app.service', verbose_name='Услуги')),
                ('transport_model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deliveries', to='app.transportmodel', verbose_name='Модель транспорта')),
            ],
            options={
                'verbose_name': 'Доставка',
                'verbose_name_plural': 'Доставки',
                'ordering': ['-departure_time'],
            },
        ),
    ]
